include $(MK_DIR)/rules.mk
include $(MK_DIR)/platform-build.mk

PKG_NAME:=linux
PKG_VERSION:=latest

download:
	git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $(PLAT_BUILD_PATH)/$(PKG_NAME)-$(PKG_VERSION)

compile:
	echo '111111'
